In [2]:
import numpy as np

In [9]:
score = [85, 90, 78, 92, 88]

curve = [s + 5 for s in score]

curve

[90, 95, 83, 97, 93]

In [8]:
score = np.array([85, 90, 78, 92, 88])

curve = score + 5

curve

array([90, 95, 83, 97, 93])

In [12]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
# 3x4 matrix of zeros

b = np.zeros((4,3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# 2x5 matrix of ones


c = np.ones((2,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
 # [0,2,4,6...18] like range()

d = np.arange(0, 20, 2)

d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# 100 evenly spaced points from 0 to 1

e = np.linspace(0, 1, 100)

e

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [22]:
# 5x3 matrix of random normal values

f = np.random.randn(5,3)

f

array([[ 0.21677332,  0.68203175,  0.68849554],
       [-1.01654183,  0.20123897, -0.67864993],
       [-0.02801653, -1.41716865, -0.82077108],
       [ 1.58506574,  2.07216698, -1.1180868 ],
       [ 0.37326121, -0.09280664, -0.02638215]])

In [25]:
# 3x3 matrix filled with 7


g = np.full((3,3), 7)

g

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [26]:
print(a.shape)

(6,)


In [27]:
print(f.ndim)

2


In [28]:
print(f.shape)

(5, 3)


In [30]:
print(f.dtype)

float64


In [31]:
print(f.size)

15


In [77]:
arr = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]
               ])

In [78]:
arr[0, 1]

np.int64(20)

In [79]:
arr[:, 1]

array([20, 50, 80])

In [38]:
arr[1, :]

array([40, 50, 60])

In [39]:
arr[0 : 2, 1 : 3]

array([[20, 30],
       [50, 60]])

In [46]:
arr[0 : 2, 1 : 2]

array([[20],
       [50]])

In [43]:
arr[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
arr[0:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
arr[0:3, 0:1]

array([[10],
       [40],
       [70]])

In [48]:
arr[0:3, 0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [51]:
arr[0:3, 1: 3]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [52]:
arr[0:2, 0:2]

array([[10, 20],
       [40, 50]])

In [53]:
arr[1:3, 0:2]

array([[40, 50],
       [70, 80]])

In [54]:
arr[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [56]:
ar = np.array([
    [6,7,8,9],
    [1,2,3,4],
    [9,8,7,6],
    [5,6,7,8]
])

In [58]:
ar.shape

(4, 4)

In [60]:
ar.size

16

In [61]:
ar.ndim

2

In [62]:
ar[0:3]

array([[6, 7, 8, 9],
       [1, 2, 3, 4],
       [9, 8, 7, 6]])

In [66]:
ar[:, 1:4]

array([[7, 8, 9],
       [2, 3, 4],
       [8, 7, 6],
       [6, 7, 8]])

In [67]:
ar[0:2, 2:4]

array([[8, 9],
       [3, 4]])

In [69]:
ar[1:4, 1:3]

array([[2, 3],
       [8, 7],
       [6, 7]])

In [71]:
ar[2:4, 2:4]

array([[7, 6],
       [7, 8]])

In [73]:
# Boolean indexing

ar[ar > 5]

array([6, 7, 8, 9, 9, 8, 7, 6, 6, 7, 8])

In [80]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [81]:
ar

array([[6, 7, 8, 9],
       [1, 2, 3, 4],
       [9, 8, 7, 6],
       [5, 6, 7, 8]])

In [82]:
arr[arr > 50]

array([60, 70, 80, 90])

In [83]:
arr[arr < 50]

array([10, 20, 30, 40])

In [84]:
arr[ arr >= 50]

array([50, 60, 70, 80, 90])

In [85]:
arr[arr <= 50]

array([10, 20, 30, 40, 50])

In [86]:
# VECTORISED OPERATIONS

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

a +b

array([11, 22, 33, 44, 55])

In [87]:
a * b

array([ 10,  40,  90, 160, 250])

In [88]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [90]:
b ** 2

array([ 100,  400,  900, 1600, 2500])

In [91]:
np.sqrt(b)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [92]:
np.log(b)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [93]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [94]:
# STATISTICAL OPERATIONS


data = np.array([23, 45, 12, 67, 34, 89, 11, 56])

In [95]:
np.mean(data)

np.float64(42.125)

In [96]:
np.max(data)

np.int64(89)

In [97]:
np.min(data)

np.int64(11)

In [98]:
np.std(data)

np.float64(25.799406485421326)

In [99]:
np.var(data)

np.float64(665.609375)

In [100]:
np.median(data)

np.float64(39.5)

In [102]:
np.argmax(data)

np.int64(5)

In [103]:
np.argmin(data)

np.int64(6)

In [104]:
np.argsort(data)

array([6, 2, 0, 4, 1, 7, 3, 5])

In [105]:
# AXIS PARAMETER AND BROADCASTING

mat = np.array([
    [5, 8, 3],
    [2, 7, 9],
    [4, 1, 6]
])


In [106]:
mat.sum(axis = 0)

array([11, 16, 18])

In [108]:
mat.max(axis = 0)

array([5, 8, 9])

In [109]:
mat.mean(axis = 0)

array([3.66666667, 5.33333333, 6.        ])

In [110]:
mat.sum(axis = 1)

array([16, 18, 11])

In [111]:
mat.max(axis = 1)

array([8, 9, 6])

In [112]:
mat.mean(axis = 1)

array([5.33333333, 6.        , 3.66666667])

In [116]:
# numpy broadcasting

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

row = np.array([10, 20, 30])

In [117]:
matrix + row

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [119]:
data = np.random.randn(100, 4)
data

array([[-0.21589714,  1.25610797, -0.07508603,  0.56927852],
       [ 0.47099508, -0.49763071,  0.9346768 , -0.86534248],
       [-0.82747019,  1.17995812,  1.63813968, -1.38143354],
       [ 0.03975657,  0.71881982,  0.06031832, -0.3673336 ],
       [-0.43050238, -0.94201058, -1.52125867,  0.26185787],
       [ 1.79095415,  0.09957031,  0.61244108, -1.37325712],
       [ 1.03366102, -0.38157272,  2.20184565, -0.32175067],
       [-0.65677389, -3.08531034, -0.71135544,  1.40447354],
       [-0.68434984, -0.88917952,  0.36161897, -0.05601589],
       [ 0.51730955, -0.89717676,  0.43665927,  0.89712556],
       [-1.04544204, -1.72598537,  1.76014331,  2.4186866 ],
       [ 1.52309431, -0.01369967,  0.21677703, -1.60508575],
       [ 0.56949525,  1.12056045,  0.93842466,  1.94408874],
       [-0.70796556,  0.34339663,  0.16146143,  0.39454375],
       [-0.74346204,  0.89381934,  0.07502337,  1.57864919],
       [-1.75560899,  0.1474448 , -0.13312738, -1.53655599],
       [ 1.70717472, -1.

In [121]:
means = data.mean(axis = 0)
means

array([ 0.01630702, -0.02325573,  0.13854479,  0.15803053])

In [123]:
mean = data.mean(axis = 1)

mean

array([ 0.38360083,  0.01067467,  0.15229852,  0.11289028, -0.65797844,
        0.2824271 ,  0.63304582, -0.76224153, -0.31698157,  0.2384794 ,
        0.35185062,  0.03027148,  1.14314227,  0.04785906,  0.45100747,
       -0.81946189, -0.14252001,  0.38657346,  0.34008279, -0.30635141,
        0.03411478,  0.71220445,  0.68898501,  0.51877927, -0.14581739,
        0.5913597 , -0.11917573, -0.30315592, -0.04629298,  0.69949147,
        0.28461858,  0.79826595, -0.82902877, -0.53773107, -0.32758167,
       -0.35528294, -0.35195517, -0.48431074, -0.12836115,  1.19944158,
       -0.29529428, -0.61531193,  0.29119206,  0.08542998, -1.33869036,
        0.86883054, -0.15343694,  0.88467336,  0.51950281, -0.55780587,
        0.15148536,  0.25476482,  0.00995233,  0.40780537, -0.66673009,
       -0.27104314, -0.43705343,  1.13740222,  0.30724082, -0.39049378,
        0.24669592,  0.41032642,  0.36940966,  0.86332844, -0.93250132,
        0.66041608,  0.34972348,  0.29376137,  0.86161327,  0.22

In [125]:
stds = data.std(axis = 0)

stds

array([0.92722747, 1.07369083, 1.06021688, 1.09718154])

In [127]:
normal = (data - means) / stds

normal

array([[-0.25042847,  1.19155688, -0.20149729,  0.37482219],
       [ 0.49037381, -0.44181711,  0.75091429, -0.93272898],
       [-0.91000022,  1.12063345,  1.41442277, -1.40310789],
       [ 0.02528997,  0.69114454, -0.07378346, -0.47883064],
       [-0.48187679, -0.85569777, -1.56553201,  0.09463095],
       [ 1.91392855,  0.1143961 ,  0.44698052, -1.39565569],
       [ 1.09720003, -0.33372455,  1.94611207, -0.43728516],
       [-0.72590699, -2.85189603, -0.80162865,  1.13604081],
       [-0.75564721, -0.80649267,  0.21040429, -0.19508752],
       [ 0.54032322, -0.81394104,  0.28118254,  0.67363057],
       [-1.14507938, -1.58586587,  1.52949699,  2.06042117],
       [ 1.625046  ,  0.0089002 ,  0.07378891, -1.60695038],
       [ 0.59660467,  1.06531242,  0.75444929,  1.62786024],
       [-0.78111638,  0.34148784,  0.02161505,  0.21556434],
       [-0.81939877,  0.85413328, -0.05991361,  1.29478907],
       [-1.91098307,  0.15898481, -0.25624208, -1.54449056],
       [ 1.82357377, -1.

In [131]:
holo = np.array([4, 6])

holo.mean(axis = 0)

np.float64(5.0)

# coding exercise

In [132]:
score = np.random.randint(40, 100, size = (50, 4))


score

array([[50, 77, 55, 96],
       [81, 70, 43, 82],
       [54, 52, 61, 57],
       [41, 66, 44, 57],
       [87, 89, 94, 53],
       [49, 95, 54, 96],
       [56, 64, 86, 58],
       [68, 94, 86, 85],
       [91, 42, 99, 65],
       [72, 81, 61, 56],
       [58, 83, 44, 54],
       [48, 64, 61, 84],
       [92, 47, 78, 51],
       [43, 53, 99, 42],
       [63, 41, 69, 95],
       [68, 55, 94, 90],
       [97, 78, 76, 52],
       [84, 40, 99, 95],
       [47, 74, 66, 97],
       [69, 94, 87, 46],
       [80, 43, 80, 85],
       [78, 55, 91, 59],
       [80, 59, 86, 45],
       [40, 97, 84, 89],
       [45, 41, 92, 60],
       [49, 42, 46, 63],
       [98, 95, 90, 97],
       [60, 79, 94, 76],
       [43, 43, 43, 50],
       [65, 78, 92, 57],
       [46, 61, 45, 48],
       [63, 56, 90, 68],
       [40, 64, 64, 41],
       [81, 43, 62, 43],
       [72, 67, 86, 95],
       [89, 75, 61, 73],
       [87, 62, 83, 76],
       [75, 54, 70, 56],
       [81, 62, 48, 96],
       [96, 69, 87, 85],


In [133]:
score.min()

np.int32(40)

In [134]:
score.max()

np.int32(99)

In [136]:
# Exercise 1
# Calculate each student's average score across all 4 exams.
# Result should have shape (50,)


avg_score = score.mean(axis = 1)

avg_score

array([69.5 , 69.  , 56.  , 52.  , 80.75, 73.5 , 66.  , 83.25, 74.25,
       67.5 , 59.75, 64.25, 67.  , 59.25, 67.  , 76.75, 75.75, 79.5 ,
       71.  , 74.  , 72.  , 70.75, 67.5 , 77.5 , 59.5 , 50.  , 95.  ,
       77.25, 44.75, 73.  , 50.  , 69.25, 52.25, 57.25, 80.  , 74.5 ,
       77.  , 63.75, 71.75, 84.25, 65.  , 72.75, 83.5 , 75.25, 68.25,
       63.5 , 62.75, 74.  , 68.  , 66.  ])

In [138]:
# Exercise 2
# Find the highest score in the entire dataset and which student
# (row index) and which exam (column index) achieved it.

highest_score = score.max()

highest_score

np.int32(99)

In [172]:
flat_index = np.argmax(score)

row, col = np.unravel_index(flat_index, score.shape)

print(f"student {row},  Exam {col}, score {score[row, col]}")

student 8,  Exam 2, score 99


In [146]:
highest_score_column = np.argmax(score,axis = 1)

highest_score_column

array([3, 3, 2, 1, 2, 3, 2, 1, 2, 1, 1, 3, 0, 2, 3, 2, 0, 2, 3, 1, 3, 2,
       2, 1, 2, 3, 0, 2, 3, 2, 1, 2, 1, 0, 3, 0, 0, 0, 3, 0, 1, 0, 2, 2,
       0, 3, 2, 2, 1, 3])

In [150]:
# Exercise 3
# Normalize the scores so that each EXAM (column) has mean=0 and std=1.
# This is called standardization — you'll use it constantly in ML.

means = score.mean(axis = 0)

means

array([67.32, 65.6 , 74.  , 69.26])

In [151]:
stds = score.std(axis = 0)

stds

array([17.43610048, 18.58494014, 17.80561709, 18.10835166])

In [153]:
normal = (score - means) / stds

normal

array([[-0.99334137,  0.61339988, -1.067079  ,  1.47666671],
       [ 0.7845791 ,  0.23675083, -1.74102362,  0.70354278],
       [-0.76393228, -0.73177529, -0.73010668, -0.67703567],
       [-1.50951183,  0.0215228 , -1.68486157, -0.67703567],
       [ 1.12869274,  1.25908396,  1.12324105, -0.89792822],
       [-1.05069365,  1.581926  , -1.12324105,  1.47666671],
       [-0.64922773, -0.08609121,  0.67394463, -0.62181253],
       [ 0.03899955,  1.52811899,  0.67394463,  0.86921219],
       [ 1.35810183, -1.26984536,  1.40405131, -0.23525057],
       [ 0.26840864,  0.8286279 , -0.73010668, -0.73225881],
       [-0.53452319,  0.93624192, -1.68486157, -0.84270508],
       [-1.10804592, -0.08609121, -0.73010668,  0.81398905],
       [ 1.4154541 , -1.00081033,  0.22464821, -1.0083745 ],
       [-1.39480729, -0.67796829,  1.40405131, -1.50538274],
       [-0.24776182, -1.32365237, -0.28081026,  1.42144357],
       [ 0.03899955, -0.57035427,  1.12324105,  1.14532788],
       [ 1.70221547,  0.

In [173]:
normal.mean(axis = 0)

array([ 3.89688282e-16,  3.13082893e-16, -1.11022302e-17, -2.62012634e-16])

In [174]:
normal.std(axis = 0)

array([1., 1., 1., 1.])

In [177]:
# Exercise 4
# Find how many students scored below 60 on AT LEAST ONE exam.


below_60 = score < 60

any_below = below_60.any(axis = 1)

count = any_below.sum()

count

np.int64(43)

In [179]:
count = (score < 60).any(axis = 1).sum()

count

np.int64(43)

In [182]:
# Exercise 5
# Give every student a 5-point bonus on exam 3 only (index 2),
# but cap the score at 100 (no score should exceed 100).

score_copy = score.copy()

score_copy[:, 2] = score_copy[:, 2] + 5

score_copy[:, 2] = np.minimum(score_copy[:, 2], 100)

score_copy

array([[ 50,  77,  60,  96],
       [ 81,  70,  48,  82],
       [ 54,  52,  66,  57],
       [ 41,  66,  49,  57],
       [ 87,  89,  99,  53],
       [ 49,  95,  59,  96],
       [ 56,  64,  91,  58],
       [ 68,  94,  91,  85],
       [ 91,  42, 100,  65],
       [ 72,  81,  66,  56],
       [ 58,  83,  49,  54],
       [ 48,  64,  66,  84],
       [ 92,  47,  83,  51],
       [ 43,  53, 100,  42],
       [ 63,  41,  74,  95],
       [ 68,  55,  99,  90],
       [ 97,  78,  81,  52],
       [ 84,  40, 100,  95],
       [ 47,  74,  71,  97],
       [ 69,  94,  92,  46],
       [ 80,  43,  85,  85],
       [ 78,  55,  96,  59],
       [ 80,  59,  91,  45],
       [ 40,  97,  89,  89],
       [ 45,  41,  97,  60],
       [ 49,  42,  51,  63],
       [ 98,  95,  95,  97],
       [ 60,  79,  99,  76],
       [ 43,  43,  48,  50],
       [ 65,  78,  97,  57],
       [ 46,  61,  50,  48],
       [ 63,  56,  95,  68],
       [ 40,  64,  69,  41],
       [ 81,  43,  67,  43],
       [ 72,  

In [184]:
score_copy.min()

np.int32(40)

In [185]:
scores = score[:, 2] + 5
score_5 = np.minimum(scores, 100)

score_5

array([ 60,  48,  66,  49,  99,  59,  91,  91, 100,  66,  49,  66,  83,
       100,  74,  99,  81, 100,  71,  92,  85,  96,  91,  89,  97,  51,
        95,  99,  48,  97,  50,  95,  69,  67,  91,  66,  88,  75,  53,
        92,  66,  70, 100, 100,  76,  58,  84,  98,  71,  71], dtype=int32)

In [163]:
m = np.random.randn(4,6)

m

array([[ 0.08472057,  1.01894467, -1.37056886, -0.93661402,  0.38040521,
         0.83907497],
       [ 0.00655451,  0.6883426 , -0.40215415,  0.36942877,  0.22464179,
        -0.79488109],
       [ 0.25712261,  0.35106279,  1.345893  , -0.018477  , -1.51495835,
         0.30796039],
       [-0.97673655,  1.67128399,  0.25609717, -1.6117201 , -1.83458268,
        -0.83142578]])

In [164]:
m.mean(axis = 0).shape

(6,)

In [165]:
m.mean(axis = 1).shape

(4,)

In [167]:
m.mean()

np.float64(-0.10377439809220163)

In [ ]:
score < 60

In [187]:
(score < 60).any(axis = 1)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [188]:
(score < 60).all(axis = 1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [189]:
(score < 60).sum()

np.int64(72)

In [190]:
(score < 60).sum(axis = 0)

array([18, 22, 10, 22])

In [191]:
np.min(score)

np.int32(40)

In [197]:
np.minimum(score, 75)

array([[50, 75, 55, 75],
       [75, 70, 43, 75],
       [54, 52, 61, 57],
       [41, 66, 44, 57],
       [75, 75, 75, 53],
       [49, 75, 54, 75],
       [56, 64, 75, 58],
       [68, 75, 75, 75],
       [75, 42, 75, 65],
       [72, 75, 61, 56],
       [58, 75, 44, 54],
       [48, 64, 61, 75],
       [75, 47, 75, 51],
       [43, 53, 75, 42],
       [63, 41, 69, 75],
       [68, 55, 75, 75],
       [75, 75, 75, 52],
       [75, 40, 75, 75],
       [47, 74, 66, 75],
       [69, 75, 75, 46],
       [75, 43, 75, 75],
       [75, 55, 75, 59],
       [75, 59, 75, 45],
       [40, 75, 75, 75],
       [45, 41, 75, 60],
       [49, 42, 46, 63],
       [75, 75, 75, 75],
       [60, 75, 75, 75],
       [43, 43, 43, 50],
       [65, 75, 75, 57],
       [46, 61, 45, 48],
       [63, 56, 75, 68],
       [40, 64, 64, 41],
       [75, 43, 62, 43],
       [72, 67, 75, 75],
       [75, 75, 61, 73],
       [75, 62, 75, 75],
       [75, 54, 70, 56],
       [75, 62, 48, 75],
       [75, 69, 75, 75],


In [194]:
maxi_score = np.maximum(score, 60)

maxi_score

array([[60, 77, 60, 96],
       [81, 70, 60, 82],
       [60, 60, 61, 60],
       [60, 66, 60, 60],
       [87, 89, 94, 60],
       [60, 95, 60, 96],
       [60, 64, 86, 60],
       [68, 94, 86, 85],
       [91, 60, 99, 65],
       [72, 81, 61, 60],
       [60, 83, 60, 60],
       [60, 64, 61, 84],
       [92, 60, 78, 60],
       [60, 60, 99, 60],
       [63, 60, 69, 95],
       [68, 60, 94, 90],
       [97, 78, 76, 60],
       [84, 60, 99, 95],
       [60, 74, 66, 97],
       [69, 94, 87, 60],
       [80, 60, 80, 85],
       [78, 60, 91, 60],
       [80, 60, 86, 60],
       [60, 97, 84, 89],
       [60, 60, 92, 60],
       [60, 60, 60, 63],
       [98, 95, 90, 97],
       [60, 79, 94, 76],
       [60, 60, 60, 60],
       [65, 78, 92, 60],
       [60, 61, 60, 60],
       [63, 60, 90, 68],
       [60, 64, 64, 60],
       [81, 60, 62, 60],
       [72, 67, 86, 95],
       [89, 75, 61, 73],
       [87, 62, 83, 76],
       [75, 60, 70, 60],
       [81, 62, 60, 96],
       [96, 69, 87, 85],


In [196]:
maxi_score.min()

np.int32(60)

In [4]:
np.random.seed(0)


# Print a formatted table header
student_score = np.random.randint(30, 100, size = (30, 5))
subject = ['math', 'english', 'science', 'history', 'cs']


header = f"{'students':<10}" + "".join(f"{sub:>10}" for sub in subject)

print(header)
print('-' * 60)


# Print each student's row

for i, row in enumerate(student_score):
    score_str = "".join(f"{val:>10}" for val in row)
    print(f"{'student'+ str(i + 1):<10}" + score_str)

students        math   english   science   history        cs
------------------------------------------------------------
student1          74        77        94        97        97
student2          39        51        66        42        88
student3          95        69        76        67        55
student4          39        50        99        77        94
student5          79        59        49        49        44
student6          69        62        95        39        87
student7          62        61        53        65        85
student8          58        64        30        30        66
student9          83        35        68        47        34
student10         72        88        61        31        95
student11         71        87        65        41        76
student12         30        44        83        42        72
student13         98        36        98        77        33
student14         82        45        50        88        53
student15         43    

In [5]:
# 1. CLASS SUMMARY
#    - Mean, median, std, min, max for each subject

student_score.mean(axis = 0)

array([64.8       , 62.33333333, 66.8       , 62.73333333, 68.66666667])

In [6]:
student_score.std(axis = 0)

array([18.50117113, 18.75159252, 23.54060322, 23.069364  , 18.18668622])

In [7]:
student_score.min(axis = 0)

array([30, 30, 30, 30, 33], dtype=int32)

In [8]:
student_score.max(axis = 0)

array([98, 94, 99, 99, 97], dtype=int32)

In [9]:
np.median(student_score, axis = 0)

array([63.5, 63. , 67. , 64. , 70.5])

In [10]:
# 2. STUDENT RANKINGS
#    - Each student's overall average

student_avg = student_score.mean(axis = 1)

student_avg

array([87.8, 57.2, 72.4, 71.8, 56. , 70.4, 65.2, 49.6, 53.4, 69.4, 68. ,
       54.2, 68.4, 63.6, 74. , 73.6, 62.6, 56.4, 66.2, 72. , 72.8, 53.4,
       58.6, 76.8, 46.4, 76. , 61.4, 59.2, 72.2, 63. ])

In [45]:
rank = np.argsort(student_avg)[:: -1]

rank

array([ 0, 23, 25, 14, 15, 20,  2, 28, 19,  3,  5,  9, 12, 10, 18,  6, 13,
       29, 16, 26, 27, 22,  1, 17,  4, 11,  8, 21,  7, 24])

In [47]:
#    - Print top 3 and bottom 3 students with their averages

print('top 3 best students')

for i, student_idx in enumerate(rank[:3]):
    print(f" #{i+1}: student {student_idx} - average : {student_avg[student_idx]:.1f}")

top 3 best students
 #1: student 0 - average : 87.8
 #2: student 23 - average : 76.8
 #3: student 25 - average : 76.0


In [67]:
#    - Rank students from best to worst (use argsort)
print('Bottom 3 students')

for i, student_idx in enumerate(rank[-3:]):
    print(f" last #{len(rank)-1}: student{student_idx} - average: {student_avg[student_idx]:.1f}")

Bottom 3 students
 last #29: student21 - average: 53.4
 last #29: student7 - average: 49.6
 last #29: student24 - average: 46.4


In [15]:
# 3. PERFORMANCE FLAGS
#    - Identify students who are "at risk": average below 50

at_risk = np.where(student_avg < 50)[0]
print('at risk students:', at_risk)
print('their averages:', student_avg[at_risk])

at risk students: [ 7 24]
their averages: [49.6 46.4]


In [17]:
#    - Identify "high performers": average above 80

high_perform = np.where(student_avg > 80)[0]
print('high performancce students:', high_perform)
print('their score:', student_avg[high_perform])

high performancce students: [0]
their score: [87.8]


In [24]:
#    - Identify students who have at least one score below 40 ("needs attention")

low_student = np.where((student_score < 40).any(axis = 1))[0]
print('need s attention:', low_student)
print('their score:', student_avg[low_student])

need s attention: [ 1  3  5  7  8  9 11 12 15 16 17 18 21 22 24 26]
their score: [57.2 71.8 70.4 49.6 53.4 69.4 54.2 68.4 73.6 62.6 56.4 66.2 53.4 58.6
 46.4 61.4]


In [57]:
# 4. NORMALIZATION
#    - Normalize each subject to 0-1 range using min-max scaling:
#      scaled = (x - min) / (max - min)

student_score.mean(axis = 0)

array([64.8       , 62.33333333, 66.8       , 62.73333333, 68.66666667])

In [58]:
mins = student_score.min(axis = 0)
mins

array([30, 30, 30, 30, 33], dtype=int32)

In [59]:
maxi = student_score.max(axis = 0)

maxi

array([98, 94, 99, 99, 97], dtype=int32)

In [60]:
scale = (student_score - mins) / (maxi - mins)

scale

array([[0.64705882, 0.734375  , 0.92753623, 0.97101449, 1.        ],
       [0.13235294, 0.328125  , 0.52173913, 0.17391304, 0.859375  ],
       [0.95588235, 0.609375  , 0.66666667, 0.53623188, 0.34375   ],
       [0.13235294, 0.3125    , 1.        , 0.68115942, 0.953125  ],
       [0.72058824, 0.453125  , 0.27536232, 0.27536232, 0.171875  ],
       [0.57352941, 0.5       , 0.94202899, 0.13043478, 0.84375   ],
       [0.47058824, 0.484375  , 0.33333333, 0.50724638, 0.8125    ],
       [0.41176471, 0.53125   , 0.        , 0.        , 0.515625  ],
       [0.77941176, 0.078125  , 0.55072464, 0.24637681, 0.015625  ],
       [0.61764706, 0.90625   , 0.44927536, 0.01449275, 0.96875   ],
       [0.60294118, 0.890625  , 0.50724638, 0.15942029, 0.671875  ],
       [0.        , 0.21875   , 0.76811594, 0.17391304, 0.609375  ],
       [1.        , 0.09375   , 0.98550725, 0.68115942, 0.        ],
       [0.76470588, 0.234375  , 0.28985507, 0.84057971, 0.3125    ],
       [0.19117647, 0.75      , 0.

In [61]:
scale.mean(axis = 0)

array([0.51176471, 0.50520833, 0.53333333, 0.47439614, 0.55729167])

In [62]:
#    - Show the mean of each subject before and after normalization


print('mean before normalization')
print(dict(zip(subject, student_score.mean(axis = 0).round(2))))

mean before normalization
{'math': np.float64(64.8), 'english': np.float64(62.33), 'science': np.float64(66.8), 'history': np.float64(62.73), 'cs': np.float64(68.67)}


In [63]:
print("\nMean per subject AFTER normalization:")
print(dict(zip(subject, scale.mean(axis=0).round(2))))


Mean per subject AFTER normalization:
{'math': np.float64(0.51), 'english': np.float64(0.51), 'science': np.float64(0.53), 'history': np.float64(0.47), 'cs': np.float64(0.56)}


In [50]:
# 5. INSIGHT
#    - Which subject has the highest failure rate? (score < 50)

failure_rate = (student_score < 50).mean(axis = 0) * 100
worst_subject_idx = np.argmax(failure_rate)

print('failure rate:', failure_rate)
print(f"Highest failure rate: {subject[worst_subject_idx]} at {failure_rate[worst_subject_idx]:.1f}")


failure rate: [23.33333333 30.         26.66666667 40.         16.66666667]
Highest failure rate: history at 40.0


In [51]:
#    - Which subject has the most consistent scores (lowest std)?

stds = student_score.std(axis = 0)
most_consistent_idx = np.argmin(stds)

print(f" most consistent subject: {subject[most_consistent_idx]} with std={stds[most_consistent_idx]:.2f}")

 most consistent subject: cs with std=18.19


In [65]:
high_rate = (student_score > 80).mean(axis = 0)* 100
best_subject_idx = np.argmax(high_rate)

print('high rate:', high_rate)
print(f" best score subject: {subject[best_subject_idx]} at {high_rate[best_subject_idx]:.1f}")

high rate: [23.33333333 20.         36.66666667 26.66666667 30.        ]
 best score subject: science at 36.7


In [ ]:
# INSIGFHT

# fro the analysis, history has the worst failure rate. 
# hence attention should be paid to history to ensure there is improvement.

# the most onsistent subject score is cs 