In [4]:
li = 9,1,8,2,7,3,6,4,5
sorted_li = sorted(li)
sorted_li

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
print('the sorted list\t', sorted_li)

the sorted list	 [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
li = -6, -5, -4, 3, 2, 1
li_1 = sorted(li, key=abs)
li_1

[1, 2, 3, -4, -5, -6]

In [5]:
student = {'name': 'michael', 'age': 25, 'courses': ['maths', 'art']}
student['phone'] = 5555
print(student)

{'name': 'michael', 'age': 25, 'courses': ['maths', 'art'], 'phone': 5555}


In [4]:
student['name'] = 'iyore'
student

{'name': 'iyore', 'age': 25, 'courses': ['maths', 'art'], 'phone': 0}

In [10]:
#to change multiple key values on a dictionary
student.update({'name': 'nolan', 'age': 26, 'phone': '234-567'})
student

{'name': 'nolan', 'age': 26, 'courses': ['maths', 'art'], 'phone': '234-567'}

In [11]:
print(student.values())

dict_values(['nolan', 26, ['maths', 'art'], '234-567'])


In [13]:
print(student.keys())

dict_keys(['name', 'age', 'courses', 'phone'])


In [14]:
print(student.items())

dict_items([('name', 'nolan'), ('age', 26), ('courses', ['maths', 'art']), ('phone', '234-567')])


In [16]:
for key in student:
    print(key)

name
age
courses
phone


In [20]:
for key, values in student.items():
    print(key,values)

name nolan
age 26
courses ['maths', 'art']
phone 234-567


loop and iteration]

In [7]:
nums = [1,2,3,4,5,6,7]
for num in nums:
    print(num, end = ' ')

1 2 3 4 5 6 7 

In [23]:
nums = [1,2,3,4,5,6,7]
for num in nums:
    if num == 3:
        print('found!')
        break
    print(num)

1
2
found!


In [24]:
for num in nums:
    if num == 3:
        print('found!')
        continue
    print(num)

1
2
found!
4
5
6
7


In [9]:
for num in nums:
    for letter in 'abc':
        print(num, letter, end = ' ')

1 a 1 b 1 c 2 a 2 b 2 c 3 a 3 b 3 c 4 a 4 b 4 c 5 a 5 b 5 c 6 a 6 b 6 c 7 a 7 b 7 c 

In [29]:
for i in range(1, 11):
    print('this is number\t', i)

this is number	 1
this is number	 2
this is number	 3
this is number	 4
this is number	 5
this is number	 6
this is number	 7
this is number	 8
this is number	 9
this is number	 10


In [31]:
x = 0
while x < 10:
    if x == 5:
        break
    print(x)
    x += 1

0
1
2
3
4


Functions

In [3]:
def hello_func():
    print('hello world function')

hello_func()

hello world function


In [5]:
def student_info(*args, **kwargs):
    print(args)
    print(kwargs)

student_info('maths', 'art', name = 'jerry', age = 45)

('maths', 'art')
{'name': 'jerry', 'age': 45}


In [7]:
courses = ['maths', 'art']
info = {'name': 'jerry', 'age': 45}

student_info(*courses, **info)

('maths', 'art')
{'name': 'jerry', 'age': 45}


In [4]:
for i in range(10):
    print('this is the range of things\t', i,)

this is the range of things	 0
this is the range of things	 1
this is the range of things	 2
this is the range of things	 3
this is the range of things	 4
this is the range of things	 5
this is the range of things	 6
this is the range of things	 7
this is the range of things	 8
this is the range of things	 9


In [10]:
square = []
for n in range(10):
    square.append(n**2)

square

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
square1 = [n**2 for n in range(10)]
square1

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [10]:
planets = ['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto']
short_planet = [planet for planet in planets if len(planet) < 6]
short_planet

['venus', 'earth', 'mars', 'pluto']

In [21]:
def has_lucky_number(nums):
    for num in nums:
        if num % 7 == 0:
            return [num % 7 == 0 for num in nums]
has_lucky_number([24,40, 49, 70])

[False, False, True, True]

In [11]:
def has_lucky_number(nums):
    return any([num % 7 == 0 for num in nums])
has_lucky_number

<function __main__.has_lucky_number(nums)>

In [22]:
[1, 2 , 3, 4] > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [23]:
def elementwise_greater_than(L, thresh):
    res = []
    for ele in L:
        res.append(ele > thresh)
    return res

In [24]:
elementwise_greater_than([1,2,3,4], 2)

[False, False, True, True]

In [18]:
def let_code(terms, foot):
    ball = []
    for play in terms:
        ball.append(play < foot)
    return ball
let_code([9,8,7,6], 2)


[False, False, False, False]

In [19]:
let_code([9,4,0,1], 2)

[False, False, True, True]

In [24]:
def menu_is_boring(meals):
    for i in range(len(meals) - 1):
        return True
    return False

NameError: name 'form' is not defined

In [28]:
def estimate_average_slot_payout(n_runs):
    payout = [play_slot_machine() - 1 for i in range(n_runs)]
    average_payout = sum(payout)/n_runs
    return average_payout

In [29]:
estimate_average_slot_payout(10000)

NameError: name 'play_slot_machine' is not defined

In [42]:
print('what\'s up')

what's up


In [41]:
print("that's \"cool\"")

that's "cool"


In [40]:
hello = "hello\nworld"
print(hello)

hello
world


In [44]:
quoted_hello = """hello 
world"""

print(quoted_hello)

hello 
world


In [47]:
date_str = '1956-12-30'
str_date = date_str.split('-')
str_date

['1956', '12', '30']

In [52]:
month, day, year = date_str.split('-')

'/'.join([month, day, year])

'1956/12/30'

In [50]:
'/'.join([month, day, year])

NameError: name 'month' is not defined

In [57]:
position = 9
planets + ', will always be the' + position + 'th planet to me'

TypeError: can only concatenate list (not "str") to list

In [61]:
position = 9
planet = 'earth', 'venus', 'pluto'

In [63]:
"{} , will always be {}th planet to me".format(planet, position)

"('earth', 'venus', 'pluto') , will always be 9th planet to me"

In [64]:
print(planets)

['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto']


In [67]:
planet_initials = {planet: planet[0] for planet in planets}
planet_initials

{'mercury': 'm',
 'venus': 'v',
 'earth': 'e',
 'mars': 'm',
 'jupiter': 'j',
 'saturn': 's',
 'uranus': 'u',
 'neptune': 'n',
 'pluto': 'p'}

In [70]:
' '.join(sorted(planet_initials.values()))

'e j m m n p s u v'

In [71]:
for planet, initial in planet_initials.items():
    print("{} begins with \"{}\"".format(planet.rjust(10), initial) )

   mercury begins with "m"
     venus begins with "v"
     earth begins with "e"
      mars begins with "m"
   jupiter begins with "j"
    saturn begins with "s"
    uranus begins with "u"
   neptune begins with "n"
     pluto begins with "p"


In [72]:
help(str.isdigit)

Help on method_descriptor:

isdigit(self, /) unbound builtins.str method
    Return True if the string is a digit string, False otherwise.

    A string is a digit string if all characters in the string are digits and there
    is at least one character in the string.



In [73]:
def word_research(doc_list, keyword):
    indices = []
    for i, doc in enumerate(doc_list):
        token = doc.split()
        normalised = [token.rstrip(' .,').lower() for token in tokens]
        if keyword.lower() in normalised:
            indices.append(i)
        return indices

In [75]:
import math

In [76]:
print('pi to 4 significant digit = {:.4}'. format(math.pi))

pi to 4 significant digit = 3.142


In [77]:
math.log(32, 2)

5.0

In [78]:
import numpy

In [82]:
rolls = numpy.random.randint(low = 1, high = 6, size = 10)
rolls

array([4, 3, 1, 5, 3, 3, 2, 5, 1, 4], dtype=int32)

In [83]:
rolls + 10

array([14, 13, 11, 15, 13, 13, 12, 15, 11, 14], dtype=int32)

In [84]:
rolls < 3

array([False, False,  True, False, False, False,  True, False,  True,
       False])

In [85]:
xlist = [[1,2,3], [2,4,6]]
x = numpy.asarray(xlist)
print('xlist = {}\nx = \n{}'. format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x = 
[[1 2 3]
 [2 4 6]]


In [19]:
students = [
    {"name": "Alice", "scores": [70, 85, 90]},
    {"name": "Bob", "scores": [60, 88, 95]},
    {"name": "Charlie", "scores": [80, 77, 82]}
]


In [30]:
def top_student(students):
    highest_score = 0
    top_student_name = ""
    
    for student in students:
        total = sum(student["score"])
        if total > highest_score:
            highest_score = total
            top_student_name = student["name"]
    return top_student_name

In [32]:
def top_student(students):
    highest_score = 0
    top_student_name = ""
    
    for student in students:
        total = sum(student["scores"])          # sum the scores
        if total > highest_score:               # compare with highest_score
            highest_score = total
            top_student_name = student["name"] # store the student name
    
    return top_student_name


In [33]:
students = [
    {"name": "Alice", "scores": [70, 85, 90]},
    {"name": "Bob", "scores": [60, 88, 95]},
    {"name": "Charlie", "scores": [80, 77, 82]}
]

print(top_student(students))


Alice


In [32]:
def top_student_odd(students):
    highest_odd_sum = 0
    top_student = ""
    
    for student in students:
        odd_scores = [score for score in student["scores"] if score % 2 != 0 ]   # get only odd scores
        total = sum(odd_scores)                                # sum the odd scores
        if total > highest_odd_sum:                               # compare total with highest_odd_sum
            highest_odd_sum = total
            top_student = student["name"]
    
    return top_student


In [33]:
students = [
    {"name": "Alice", "scores": [70, 85, 90]},
    {"name": "Bob", "scores": [60, 88, 95]},
    {"name": "Charlie", "scores": [80, 77, 82]}
]

print(top_student_odd(students))

Bob


In [45]:
def top_odd_student(students):
    highest_odd_score = 0
    top_student = ''
    for student in students:
        odd_score = [score for score in student["scores"] if score % 2 != 0] #to get the odd score
        total = sum(odd_score)                                        #to get the sum of the odd score
        if total > highest_odd_score:                             #comparing the odd score 
            highest_odd_score = total
            top_student = student['name']
    return top_student

In [48]:
students = [
    {"name": "Alice", "scores": [70, 85, 90]},
    {"name": "Bob", "scores": [60, 88, 95]},
    {"name": "Charlie", "scores": [80, 77, 82]}
]

print(top_odd_student(students))

Bob


In [67]:
def even_num(nums):
    total = 0
    for num in nums:
        if num % 2 == 0:
            total += num
    return total

In [68]:
even_num([2,4,6,8,9])

20

In [88]:
def tenx(aboveten):
    tenabove = 0
    for ten in aboveten:
        if ten > 10:
            tenabove += 1
    return tenabove

In [89]:
tenx([3,5,7,84,10,34,6])

2

In [77]:
def num_greater(numbs):
    num = 0                  # Step 1: counter
    for n in numbs:          # Step 2: loop through list
        if n > 10:           # Step 3: check condition
            num += 1         # Step 4: increase counter
    return num               # Step 5: return counter

In [79]:
num_greater([3,5,7,84,10,34,6])

2

In [81]:
def get_odd(odd_numbers):
    odd_num = []                     #created an empty list
    for odd in odd_numbers:           #loop through the list to get the odd numbers
        if odd % 2 != 0:
            odd_num.append(odd)
    return odd_num

In [82]:
print(get_odd([1, 2, 3, 4, 5, 11, 14, 17]))


[1, 3, 5, 11, 17]


In [83]:
print(get_odd([1, 2, 3, 4, 5, 10, 11, 13, 18, 21]))


[1, 3, 5, 11, 13, 21]


In [84]:
def largest_numb(numbers):
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest

In [85]:
largest_numb([4, 9, 2, 17, 6])

17

In [96]:
def highest_odd(numbers):
    odd_numb = []
    for num in numbers:
        if num % 2 != 0:
            odd_numb.append(num)
    if not numbers:
        return none
        
    largest = odd_numb[0]
    for numb in odd_numb:
        if numb > largest:
            largest = numb
    return largest
    

In [97]:
highest_odd([4, 7, 2, 9, 12])

9

In [102]:
def sublist(numbers):
    odd_sub = 0
    for numb in numbers:
        sum_odd = 0
        for n in numb:
            if n % 2 != 0:
                sum_odd += n
        if sum_odd > odd_sub:
            odd_sub = sum_odd
    return odd_sub

In [104]:
print(sublist(([[1,2,3], [4,5,6,7], [8,9]])))

12


In [105]:
def largest_odd_sum(sublists):
    largest_sum = 0
    for sublist in sublists:
        sub_sum = 0
        for n in sublist:
            if n % 2 != 0:           # check if n is odd
                sub_sum += n          # add n to sub_sum
        if sub_sum > largest_sum:     # compare sub_sum with largest_sum
            largest_sum = sub_sum
    return largest_sum


In [106]:
print(largest_odd_sum([[1,2,3], [4,5,6,7], [8,9]]))

12


In [123]:
def school_result(students):
    highest_score = 0
    top_student = ''
    for student in students:
        total = sum(student['scores'])
        if total > highest_score:
            highest_score = total
            top_student = student['name']
    return top_student

In [124]:
students = [
    {"name": "Alice", "scores": [70, 85, 90]},
    {"name": "Bob", "scores": [60, 88, 95]},
    {"name": "Charlie", "scores": [80, 77, 82]}
]

print(school_result(students))


Alice
