In [1]:
import numpy as np

In [2]:
soccer = np.array([70, 85, 90, 60, 78])
soccer

array([70, 85, 90, 60, 78])

In [4]:
soccer.mean()

np.float64(76.6)

In [5]:
soccer.max()


np.int64(90)

In [6]:
soccer.min()

np.int64(60)

In [9]:
np.sort(soccer)

array([60, 70, 78, 85, 90])

In [7]:
np.median(soccer)

np.float64(78.0)

In [8]:
np.percentile(soccer, 25)

np.float64(70.0)

In [10]:
np.percentile(soccer, 75)

np.float64(85.0)

In [25]:
score = np.array([70, 85, 90, 60, 78, 200])

In [26]:
score

array([ 70,  85,  90,  60,  78, 200])

In [27]:
np.sort(score)

array([ 60,  70,  78,  85,  90, 200])

In [28]:
Q1 = np.percentile(score, 25)
Q1

np.float64(72.0)

In [29]:
Q3 = np.percentile(score, 75)
Q3

np.float64(88.75)

In [30]:
IQR = Q3 - Q1
IQR

np.float64(16.75)

In [31]:
lower_bound = Q1 - 1.5 * 16.75


lower_bound

np.float64(46.875)

In [32]:
higher_bound = Q3 + 1.5 * 16.75
higher_bound

np.float64(113.875)

In [34]:
outlier = score[(score < lower_bound) | (score > higher_bound)]
outlier

array([200])

In [36]:
mat = np.array([[1, 2, 3],
    [4, 5, 6]
])

mat

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
mat.shape

(2, 3)

In [38]:
mat.ndim

2

In [39]:
mat.size

6

In [40]:
mat.dtype

dtype('int64')

In [42]:
# creating special array
# zeros and ones

np.zeros(5)
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [47]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
num = np.array([10, 20, 30, 40, 50])
num

array([10, 20, 30, 40, 50])

In [49]:
num[1]

np.int64(20)

In [51]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
mat[1, 2]

np.int64(6)

In [52]:
mat[0,1]

np.int64(2)

In [53]:
mat[1,1]

np.int64(5)

In [55]:
nums = np.array([45, 67, 89, 90, 55, 72, 100, 30])
nums

array([ 45,  67,  89,  90,  55,  72, 100,  30])

In [56]:
nums.mean()

np.float64(68.5)

In [57]:
nums.max()

np.int64(100)

In [59]:
nums.min()

np.int64(30)

In [67]:
nums[nums > 70]

array([ 89,  90,  72, 100])

In [68]:
nums + 5

array([ 50,  72,  94,  95,  60,  77, 105,  35])